// Audited unchanged September 9 import copies. Preserve canonical edits and unmatched items.
export const DUPLICATE_PAIRS = [
  {
    canonicalId: "0Zbs3CcMXJnuYYwKtZog",
    duplicateId: "tU4MBZZaOw82Noce7XUf",
    duplicateData: {
      section: "pasta",
      note: "",
      price: "₪85",
      desc: "עם פירות ים ברוטב שמנת לימון.",
      order: 3,
      photo: "images/פסטה Seafood.jpg",
      name: "פסטה Seafood",
    },
  },
  {
    canonicalId: "0r1GSiNPcO3OeF6XGg0E",
    duplicateId: "AD2TlKh3z0n3LRz7DnEF",
    duplicateData: {
      section: "snacks",
      note: "",
      price: "₪45",
      desc: "קריספיות ונמסות.",
      order: 2,
      photo: "",
      name: "אצבעות מוצרלה",
    },
  },
  {
    canonicalId: "OdMwQLuBcDQjfgHONmxG",
    duplicateId: "0vBbdDmsGvHCfAVdMJ9X",
    duplicateData: {
      note: "",
      order: 1,
      photo: "",
      desc: "בציפוי זהוב עדין.",
      section: "snacks",
      name: "כדורי פירה",
      price: "₪35",
    },
  },
  {
    canonicalId: "0xAysKvpeZsAdFeVBB7c",
    duplicateId: "gcUCaUOgJcAbRwSEK4fN",
    duplicateData: {
      price: "₪75",
      name: "סלט טוסט בלאנקו",
      section: "salads",
      note: "",
      desc: "מיקס ירקות מרענן בטעם פסטו, קוביות טוסט ביגל ממולא גבינות. פשוט, מדויק, ממכר.",
      order: 2,
      photo: "images/סלט טוסט בלאנקו.jpg",
    },
  },
  {
    canonicalId: "c8lptcEHYFvepPSJbYeG",
    duplicateId: "1Jx5IqZuTx9wwa52lg6O",
    duplicateData: {
      name: "מדליון פילה אנגוס",
      price: "₪149",
      desc: "בטעם ארגנטינאי.",
      section: "mains",
      note: "לבחירה על מצע: פירה / רביולי / ריזוטו",
      photo: "images/מדליון פילה אנגוס.jpg",
      order: 5,
    },
  },
  {
    canonicalId: "72eZVxZ35JIVev9A3zaP",
    duplicateId: "1QLkXBh0Ga51Ue0AR92Q",
    duplicateData: {
      name: "כריך פילה",
      section: "sandwiches",
      photo: "",
      order: 8,
      desc: "מוגש עם ירקות ובצל בטעם צ׳ימיצ׳ורי.",
      note: "",
      price: "₪55",
    },
  },
  {
    canonicalId: "pBlrTeEp5zdDz9Snuhlj",
    duplicateId: "1dSwceakvvn0TorCm1nR",
    duplicateData: {
      photo: "images/רביולי.jpg",
      order: 1,
      desc: "במילוי גבינה או בטטה, ברוטב שמנת פטריות.",
      section: "pasta",
      note: "",
      price: "₪69",
      name: "רביולי",
    },
  },
  {
    canonicalId: "95Wu9vf1FSMmv5VjcSHk",
    duplicateId: "5omVAgqK1zzRa1HPoaUE",
    duplicateData: {
      order: 0,
      photo: "images/סלט קיסר בלאנקו.jpg",
      name: "סלט קיסר בלאנקו",
      section: "salads",
      price: "₪59",
      note: "תוספת חזה עוף ₪12",
      desc: "מיקס חסה צבעים, קרוטונים מוזהבים, רוטב קיסר עשיר ופטריות טריות, עם פרמזן וצנוברים.",
    },
  },
  {
    canonicalId: "Ew6vKwKSfk5A7ojh2rh4",
    duplicateId: "6G4YvulueogDeCR2Ly1D",
    duplicateData: {
      section: "pasta",
      price: "₪85",
      name: "פסטה סלמון",
      note: "",
      desc: "קוביות סלמון ברוטב שמנת לימון.",
      photo: "",
      order: 2,
    },
  },
  {
    canonicalId: "6imPNpPOukXK8NJrJp22",
    duplicateId: "p2RzNN9CozQ7App0WJdt",
    duplicateData: {
      note: "",
      desc: "שילוב גבינות ונקניקים עם פטריות טריות ופסטו.",
      order: 7,
      photo: "images/טוסט ארבע עונות.jpg",
      section: "sandwiches",
      name: "טוסט משולב",
      price: "₪49",
    },
  },
  {
    canonicalId: "WX6dUzFfda221Zb5gVdz",
    duplicateId: "8jttFhsKHNdASY5VAMHq",
    duplicateData: {
      photo: "images/חזה עוף.jpg",
      order: 0,
      name: "חזה עוף",
      price: "₪86",
      note: "לבחירה: ריזוטו / רביולי בטטה / צ׳יפס",
      desc: "בטעם איטלקי עדין.",
      section: "mains",
    },
  },
  {
    canonicalId: "JSqNM4cggVJKIs2gwBxU",
    duplicateId: "9K2wsX6nGZU15WVxaZFi",
    duplicateData: {
      section: "breakfast",
      price: "₪79",
      note: "",
      desc: "הבוקר שלך, בסטנדרט שלנו. ביצים לבחירה, מבחר מטבלים מובחרים, סלט שוק טרי ולחם הבית החם.",
      photo: "images/בוקר זוגי בלאנקו.jpg",
      order: 1,
      name: "בוקר בלאנקו / יחיד",
    },
  },
  {
    canonicalId: "ld11h8rBZMbytdKnnycX",
    duplicateId: "9quJToKZs9qWXhFYD0EA",
    duplicateData: {
      note: "",
      desc: "גבינת חלומי צרובה, ירקות טריים, ממרח בלאנקו ופסטו / אבוקדו.",
      price: "₪45",
      section: "sandwiches",
      name: "כריך חלומי צרובה",
      photo: "images/כריך חלומי צרובה.jpg",
      order: 0,
    },
  },
  {
    canonicalId: "AaNWE5Lqf9HZfp4j7Osi",
    duplicateId: "aSFVKBD1RHlXJPuvnsP6",
    duplicateData: {
      section: "mezazak",
      price: "₪65",
      name: "ג׳בטה עוף מוקרם",
      note: "",
      desc: "רצועות עוף ברוטב שמנת פטריות ופסטו.",
      order: 4,
      photo: "images/ג׳בטה עוף מוקרם.jpg",
    },
  },
  {
    canonicalId: "BDliGrKKG1o3wVJWL9B5",
    duplicateId: "Obqw3VoZL77ZoTR4QHbG",
    duplicateData: {
      price: "₪109",
      section: "mezazak",
      name: "קורדון בלו",
      order: 1,
      photo: "images/קורדון בלו.jpg",
      note: "",
      desc: "עוף ממולא גבינות, עם רוטב שמנת חרדל עדין ומאוזן.",
    },
  },
  {
    canonicalId: "BDu1eUyA0BfOBC5Iiyyp",
    duplicateId: "NMobOyqUo9rkWAnmvb3L",
    duplicateData: {
      desc: "שניצל עוף פריך, ירקות טריים וממרח בלאנקו ופסטו.",
      price: "₪45",
      note: "",
      order: 2,
      photo: "images/כריך שניצל קריספי.jpg",
      section: "sandwiches",
      name: "כריך שניצל קריספי",
    },
  },
  {
    canonicalId: "DapUBn6CIHvbO5MBZRyy",
    duplicateId: "i4es4eHLpEfYLvIquN9c",
    duplicateData: {
      section: "kids",
      order: 0,
      photo: "images/שניצלונים.jpg",
      name: "שניצלונים",
      price: "₪35",
      desc: "מוגש לצד צ׳יפס פריך.",
      note: "",
    },
  },
  {
    canonicalId: "G8kYqWVyUMRomnHx2TPf",
    duplicateId: "ue6kQ7gUn1aoGBFKOJo1",
    duplicateData: {
      price: "₪55",
      note: "",
      desc: "בייקון איכותי, ירקות טריים, ממרח בלאנקו ופסטו.",
      order: 1,
      photo: "images/כריך בייקון פרימיום.jpg",
      section: "sandwiches",
      name: "כריך בייקון פרימיום",
    },
  },
  {
    canonicalId: "GAutCJ9GITHLhlZAYssy",
    duplicateId: "vHnLmM5Ithxh2OgWu78D",
    duplicateData: {
      name: "כריך בלאנקו",
      section: "sandwiches",
      photo: "images/כריך בלאנקו.jpg",
      order: 5,
      note: "",
      price: "₪45",
      desc: "מבחר גבינות ונקניקים איכותיים, ירקות טריים וממרח בלאנקו ופסטו.",
    },
  },
  {
    canonicalId: "OA4gpmB3PSf62xEbfDpL",
    duplicateId: "GWbhQJadRwopKDt6geVc",
    duplicateData: {
      name: "לינגוויני",
      photo: "images/לינגוויני.jpg",
      order: 0,
      note: "",
      price: "₪69",
      desc: "ברוטב לבחירה: שמנת פטריות / רוזה / נפוליטנה.",
      section: "pasta",
    },
  },
  {
    canonicalId: "Gzyzw8vrsrgwzLacrjza",
    duplicateId: "TOXfyPIs6b0CcqEAOH7t",
    duplicateData: {
      desc: "פרוסות דקות של בשר מובחר בתיבול עדין של בלסמי, פרמזן, בפרזנטציה אלגנטית.",
      section: "mezazak",
      order: 3,
      note: "",
      photo: "images/קרפצ׳יו בקר.jpg",
      name: "קרפצ׳יו בקר",
      price: "₪79",
    },
  },
  {
    canonicalId: "mlNvMVufnrHpMyIYHjKB",
    duplicateId: "HaP4nICTABhz0mioO58R",
    duplicateData: {
      price: "₪119",
      name: "צלעות לבן בטעם השף",
      section: "mains",
      order: 7,
      photo: "images/צלעות לבן בטעם השף.jpg",
      note: "לבחירה על מצע: פירה / רביולי / ריזוטו",
      desc: "",
    },
  },
  {
    canonicalId: "IBVHm8s2JOgPWqdCVWIX",
    duplicateId: "OPioZOj8bMBGsf5gMacj",
    duplicateData: {
      name: "פוקצ׳ה שום",
      order: 1,
      photo: "",
      note: "",
      price: "₪19",
      desc: "אפויה במקום, בנגיעות שמן זית.",
      section: "mezze",
    },
  },
  {
    canonicalId: "gQXFuWnwlNKJvoLwHa1o",
    duplicateId: "JOMA5MDMkpQCjEZJaROz",
    duplicateData: {
      price: "₪69",
      name: "סלט חלומי צרובה",
      section: "salads",
      note: "",
      order: 1,
      photo: "images/סלט חלומי צרובה.jpg",
      desc: "ירקות שוק צבעוניים, גבינת חלומי צרובה מושלמת עם פטריות ואגוזי מלך בטעם אסייאתי.",
    },
  },
  {
    canonicalId: "K0tQDDO4RMFowJafnygc",
    duplicateId: "YVaKAkfxyQu2nCsIgh19",
    duplicateData: {
      photo: "images/שניצל פריך עם צ׳יפס.jpg",
      order: 0,
      name: "שניצל פריך עם צ׳יפס",
      price: "₪69",
      desc: "",
      section: "mezazak",
      note: "",
    },
  },
  {
    canonicalId: "LbpwLp1nS95Ml8E0dRTn",
    duplicateId: "KJ2dDsF4ubLSw7sAPCqp",
    duplicateData: {
      price: "₪49",
      section: "sandwiches",
      name: "טוסט ארבע עונות",
      order: 6,
      photo: "images/טוסט ארבע עונות.jpg",
      note: "",
      desc: "שילוב גבינות עשיר ומעודן עם פטריות טריות ופסטו.",
    },
  },
  {
    canonicalId: "yiYNDmKI7Q4FUOzpXQvU",
    duplicateId: "Kldmbuy0xPntKzzpPRWu",
    duplicateData: {
      name: "הום פריייז בלאנקו",
      order: 0,
      photo: "images/הום פריייז בלאנקו.jpg",
      section: "snacks",
      price: "₪35",
      desc: "",
      note: "",
    },
  },
  {
    canonicalId: "LVCd7yiW1bsdubVw1HLS",
    duplicateId: "tIrgaC2OCtOuPIB0iojb",
    duplicateData: {
      order: 3,
      photo: "images/טאבולה בלאנקו.jpg",
      desc: "מוגש עם גבינת פטה מוקצפת ורימונים טריים. איזון מדויק של רעננות ועומק.",
      note: "",
      name: "טאבולה בלאנקו",
      price: "₪59",
      section: "salads",
    },
  },
  {
    canonicalId: "UOF9F8wcxjezZwkHfB0I",
    duplicateId: "LmbjdP1bSDMmSyvmCc24",
    duplicateData: {
      note: "",
      price: "₪45",
      section: "sandwiches",
      desc: "מוגש בג׳בתה דגנים עם טונה וביצה קשה, ירקות טריים וממרח בלאנקו ופסטו.",
      order: 4,
      photo: "images/כריך Fitness.jpg",
      name: "כריך Fitness",
    },
  },
  {
    canonicalId: "M66yXii07c4ZimD6LGDl",
    duplicateId: "pTe3AvtaU59rQurRjnvL",
    duplicateData: {
      name: "צ׳יפס",
      section: "snacks",
      photo: "",
      order: 3,
      desc: "",
      price: "גדול ₪30 · קטן ₪15",
      note: "",
    },
  },
  {
    canonicalId: "as4zR12I5EETrpzTrz5q",
    duplicateId: "NJCzYs9xXUEc1c84VeNl",
    duplicateData: {
      name: "כריך נקניקיות צ׳דר",
      price: "₪25",
      section: "kids",
      note: "",
      desc: "בלחם טרי.",
      order: 1,
      photo: "",
    },
  },
  {
    canonicalId: "XNUmey7esXit5x5GJ8xE",
    duplicateId: "Nurej5PeouIBO1iKKjlr",
    duplicateData: {
      section: "mains",
      price: "₪105",
      desc: "מטוגן / ברוטב שום לימון.",
      note: "",
      order: 4,
      photo: "",
      name: "מקס פירות ים",
    },
  },
  {
    canonicalId: "PbiO2UWhODPIjqmt2UQg",
    duplicateId: "l3Ia3UOnmkbou30Hy1wi",
    duplicateData: {
      name: "שקשוקה בלאנקו",
      section: "breakfast",
      order: 2,
      photo: "images/שקשוקה בלאנקו.jpg",
      note: "",
      price: "₪75",
      desc: "עגבניות בבישול איטי, תיבול מדויק וביצים רכות במרכז. מוגשת עם 3 סוגי מטבלים מובחרים, סלט טרי ולחם הבית. מוגש עם מיץ טבעי סחוט ומשקה חם לבחירה.",
    },
  },
  {
    canonicalId: "YzHYDo466w3JqnuNyaCg",
    duplicateId: "RIHVffd4F10hXadgsB0J",
    duplicateData: {
      order: 6,
      photo: "images/מוקפץ טיוואן.jpg",
      section: "mezazak",
      note: "תוספות: חזה עוף / רצועות פילה / סינטה לבן — ₪19",
      desc: "ירקות אסיאתיים בטעם פיקנטי-מתוק.",
      price: "₪49",
      name: "מוקפץ טיוואן",
    },
  },
  {
    canonicalId: "V8BHcN8zio5YWrnXAuLq",
    duplicateId: "ZBKFfvsrhiRmUuzBq1ph",
    duplicateData: {
      desc: "עלים, מלפפון ועגבנייה טריים, קרוטונים בניחוח סומאק וזעתר, עם גבינה ובודוק קלוי. טעמים יסתיכוניים בנגיעה מודרנית.",
      section: "salads",
      price: "₪69",
      note: "",
      order: 4,
      photo: "images/פתוש בלאנקו.jpg",
      name: "פתוש בלאנקו",
    },
  },
  {
    canonicalId: "W4sG00Zzbpxo0x13rg02",
    duplicateId: "gbHDhqVxJgrfVrzCQbkY",
    duplicateData: {
      price: "₪55",
      name: "מזה בלאנקו",
      desc: "",
      photo: "images/מזה בלאנקו.jpg",
      order: 0,
      section: "mezze",
      note: "תוספת קוויאר ₪20",
    },
  },
  {
    canonicalId: "WetWW4AVWpWD6pmsVaQy",
    duplicateId: "nFZVpLeJem0RqXv5j9Bk",
    duplicateData: {
      photo: "images/מטוגני חמאתי.jpg",
      order: 2,
      name: "מטוגני חמאתי",
      price: "₪39",
      section: "mezazak",
      desc: "",
      note: "",
    },
  },
  {
    canonicalId: "l4LtqP1TBZQMj82Qbrmw",
    duplicateId: "Ydkf9KHD3X5CUi0IPQCW",
    duplicateData: {
      note: "",
      price: "₪105",
      desc: "מטוגן / ברוטב שום לימון.",
      order: 2,
      photo: "",
      section: "mains",
      name: "שרימפס",
    },
  },
  {
    canonicalId: "zQAM8roY7aftmyMVylVI",
    duplicateId: "b7V64KlRXYmzHdOlLafp",
    duplicateData: {
      price: "₪15",
      note: "",
      desc: "מרקם עדין, נגיעה מתוקה.",
      order: 3,
      photo: "",
      section: "kids",
      name: "יווני ילדים",
    },
  },
  {
    canonicalId: "qxwlbE26nn1ars85oGht",
    duplicateId: "bMvqCVTWE4NAa0jt46eG",
    duplicateData: {
      section: "mains",
      price: "₪95",
      desc: "מטוגן / ברוטב שום לימון.",
      note: "",
      photo: "",
      order: 3,
      name: "קלמארי",
    },
  },
  {
    canonicalId: "bXWSqaXQskYwcQvTP8ca",
    duplicateId: "bhaFxCgLtRfdcgfWIYgm",
    duplicateData: {
      desc: "",
      note: "",
      section: "mezze",
      price: "₪75",
      name: "קלמארי עם לבנה חריפה",
      order: 3,
      photo: "images/קלמארי עם לבנה חריפה.jpg",
    },
  },
  {
    canonicalId: "ce1qHIrfXRX6BBxwb7qq",
    duplicateId: "zKrezuoJHT5cYODCZAO1",
    duplicateData: {
      price: "₪35",
      section: "kids",
      name: "בורגר קריספי",
      note: "",
      photo: "",
      order: 2,
      desc: "מוגש עם צ׳יפס.",
    },
  },
  {
    canonicalId: "sICS2G8gIc7pIfFtRUVk",
    duplicateId: "e2mUOuy9fuM7K6wpkDxP",
    duplicateData: {
      name: "בורגר קריספי",
      section: "mezazak",
      order: 5,
      photo: "images/בורגר קריספי.jpg",
      desc: "עוף קריספי עסיסי בלחמנייה בוטיק.",
      note: "תוספת גבינת צ׳דר ₪5 | תוספת בייקון ₪10",
      price: "₪45",
    },
  },
  {
    canonicalId: "fT1QYso4hwYDWIWoUM6B",
    duplicateId: "fguYKL71garwae20iv6g",
    duplicateData: {
      note: "",
      order: 3,
      photo: "",
      desc: "חביתה אוורירית, ירקות טריים וממרח לבנה / אבוקדו.",
      name: "כריך חביתה קלאסית",
      section: "sandwiches",
      price: "₪45",
    },
  },
  {
    canonicalId: "k7DpoTURmXbLJZrNEyI4",
    duplicateId: "lG7hMzntRiK1OObmgtIZ",
    duplicateData: {
      name: "סלמון",
      price: "₪109",
      note: "לבחירה: ריזוטו / רביולי בטטה / צ׳יפס",
      desc: "צרוב במחבת בנגיעות עשבי תיבול.",
      section: "mains",
      photo: "images/salmon.jpg",
      order: 1,
    },
  },
  {
    canonicalId: "nNetxVfQ7LCUEDBpaYxh",
    duplicateId: "tgeFk1OoAJrzu0MxCW1c",
    duplicateData: {
      desc: "קרואסון חמאה צרפתי פריך, במילוי פסטו טרי, ממרח בלאנקו וירקות רעננים, עם סלמון מעושן איכותי. מוגש עם 3 סוגי מטבלים מובחרים. מוגש עם לימונדה קרה ומשקה חם לבחירה.",
      price: "₪65",
      note: "",
      photo: "images/קרואסון בלאנקו ספיישל.jpg",
      order: 3,
      section: "breakfast",
      name: "קרואסון בלאנקו ספיישל",
    },
  },
  {
    canonicalId: "zessvn39qu2akCiywI6G",
    duplicateId: "tPBZVYZMGZHvpvZaXHgI",
    duplicateData: {
      name: "חתן לבן – סינטה לבן",
      price: "₪119",
      section: "mains",
      desc: "",
      note: "לבחירה על מצע: פירה / רביולי / ריזוטו",
      order: 6,
      photo: "",
    },
  },
  {
    canonicalId: "ylfVm5LyVfCwstceOjPw",
    duplicateId: "vVhWgrBLIMszPKrzluT9",
    duplicateData: {
      price: "₪35",
      name: "אדממי מלוח",
      section: "mezze",
      order: 2,
      photo: "",
      note: "",
      desc: "",
    },
  },
];
